import { useMemo } from "react"
import type {
  TabsParams,
  StatisticsTabsState,
} from "@/components/app/statistics-charts/hooks/ui-models/types"

export function useStatisticsTabsModel(params: TabsParams): StatisticsTabsState {
  const {
    hasData,
    effectiveDisplayMode,
    selectedDiscipline,
    totalDisciplineShots,
    lineChartConfig,
    lineData,
    lineChartTicks,
    resultTrendYAxis,
    metricLabel,
    barData,
    disciplineFilter,
    seriesChartConfig,
    seriesYAxis,
    seriesHasDecimals,
    filteredHitLocations,
    showCloudTrail,
    setShowCloudTrail,
    hitLocationCloudChartConfig,
    hitLocationCloudAxes,
    displayTimeZone,
    hitLocationCloudCurveSegments,
    hitLocationCloudPathStart,
    hitLocationCloudPathEnd,
    hitLocationMetrics,
    showHitLocationTrendX,
    showHitLocationTrendY,
    setShowHitLocationTrendX,
    setShowHitLocationTrendY,
    hitLocationTrendChartConfig,
    hitLocationTrendData,
    hitLocationTrendTicks,
    hitLocationTrendAxis,
    showHitLocationTrendXSeries,
    showHitLocationTrendYSeries,
    radarChartData,
    filteredRadarSessionsCount,
    radarDateLabel,
    radarChartConfig,
    radarLegendItems,
    filteredWellbeingCount,
    wellbeingChartConfig,
    wellbeingYAxis,
    wellbeingScoreLabel,
    wellbeingDisplayData,
    filteredQualityCount,
    qualityChartConfig,
    qualityYAxis,
    qualityScoreLabel,
    qualityDisplayData,
    aggregatedShotDistribution,
    shotDistributionChartConfig,
    shotDistributionTicks,
  } = params

  return useMemo<StatisticsTabsState>(() => {
    return {
      trend: {
        hasData,
        resultTrend: {
          effectiveDisplayMode,
          selectedDiscipline,
          totalDisciplineShots,
          lineChartConfig,
          lineData,
          lineChartTicks,
          resultTrendYAxis,
          metricLabel,
        },
        seriesRatings: {
          barData,
          disciplineFilter,
          seriesChartConfig,
          seriesYAxis,
          seriesHasDecimals,
        },
      },
      hitLocation: {
        cloud: {
          filteredHitLocations,
          showCloudTrail,
          onToggleCloudTrail: () => setShowCloudTrail((current) => !current),
          hitLocationCloudChartConfig,
          hitLocationCloudAxes,
          displayTimeZone,
          hitLocationCloudCurveSegments,
          hitLocationCloudPathStart,
          hitLocationCloudPathEnd,
          hitLocationMetrics,
        },
        trend: {
          displayTimeZone,
          showHitLocationTrendX,
          showHitLocationTrendY,
          onToggleHitLocationTrendX: () => setShowHitLocationTrendX((current) => !current),
          onToggleHitLocationTrendY: () => setShowHitLocationTrendY((current) => !current),
          hitLocationTrendChartConfig,
          hitLocationTrendData,
          hitLocationTrendTicks,
          hitLocationTrendAxis,
          showHitLocationTrendXSeries,
          showHitLocationTrendYSeries,
        },
      },
      selfAssessment: {
        radarChartData,
        filteredRadarSessionsCount,
        radarDateLabel,
        radarChartConfig,
        radarLegendItems,
      },
      wellbeing: {
        filteredWellbeingCount,
        wellbeingChartConfig,
        wellbeingYAxis,
        wellbeingScoreLabel,
        wellbeingDisplayData,
        effectiveDisplayMode,
        selectedDiscipline,
      },
      quality: {
        scatter: {
          filteredQualityCount,
          qualityChartConfig,
          qualityYAxis,
          qualityScoreLabel,
          qualityDisplayData,
          effectiveDisplayMode,
          selectedDiscipline,
        },
        distribution: {
          aggregatedShotDistribution,
          shotDistributionChartConfig,
          shotDistributionTicks,
        },
      },
    }
  }, [
    aggregatedShotDistribution,
    barData,
    disciplineFilter,
    displayTimeZone,
    effectiveDisplayMode,
    filteredHitLocations,
    filteredQualityCount,
    filteredRadarSessionsCount,
    filteredWellbeingCount,
    hasData,
    hitLocationCloudAxes,
    hitLocationCloudChartConfig,
    hitLocationCloudCurveSegments,
    hitLocationCloudPathEnd,
    hitLocationCloudPathStart,
    hitLocationMetrics,
    hitLocationTrendAxis,
    hitLocationTrendChartConfig,
    hitLocationTrendData,
    hitLocationTrendTicks,
    lineChartConfig,
    lineChartTicks,
    lineData,
    metricLabel,
    qualityChartConfig,
    qualityDisplayData,
    qualityScoreLabel,
    qualityYAxis,
    radarChartConfig,
    radarChartData,
    radarDateLabel,
    radarLegendItems,
    resultTrendYAxis,
    selectedDiscipline,
    seriesChartConfig,
    seriesHasDecimals,
    seriesYAxis,
    setShowCloudTrail,
    setShowHitLocationTrendX,
    setShowHitLocationTrendY,
    shotDistributionChartConfig,
    shotDistributionTicks,
    showCloudTrail,
    showHitLocationTrendX,
    showHitLocationTrendXSeries,
    showHitLocationTrendY,
    showHitLocationTrendYSeries,
    totalDisciplineShots,
    wellbeingChartConfig,
    wellbeingDisplayData,
    wellbeingScoreLabel,
    wellbeingYAxis,
  ])
}
